### ISSUE TITLE
Please help to transform FbonizziMonoGameGallery project from WPF into UWP

### ISSUE THREAD

**Issue by mediaexplorer74** [FrancescoBonizzi/FbonizziMonoGame#13]
Hi [Francesco](https://github.com/FrancescoBonizzi).

I'm big fan(boy) of cancelled Windows Phone (eco)system. I still interested in Windows 10 Mobile OS. As hobby, I created https://github.com/mediaexplorer74/W10MGameDevQuickie. I transform your multi-platform InFart and StarFall games into W10M-compatible UWP apps (min. W10M build = 15063). Also I added to W10MGameDevQuickie some other open-sorced retro-games. My biggest problem is: 
- I old and stupid, I cancelled and professianal (commerce) app coding (developing). 
- Idk how to incapsulate (inject) your [FbonizziMonoGame](https://github.com/FrancescoBonizzi/FbonizziMonoGame) library into some simple game like/as Snake on NuPogodi (Rus. clone of similar old Nintendo game).
Please help me to transform "forced/injected"[https://github.com/mediaexplorer74/W10MGameDevQuickie/tree/master/Src/FbonizziMonoGameGallery](https://github.com/mediaexplorer74/W10MGameDevQuickie/tree/master/Src/FbonizziMonoGameGallery) project from WPF into UWP, if you can (have some free time). 

You're the great developer in my mind!

Great wishes, and Marry Christmas,

Andrey aka MediaExplorer74

**Comment by FrancescoBonizzi** [comment]
Hi @mediaexplorer74, what a wonderful job, I'm impressed! 😱 Thanks for everything!

I didn't understand if you want to port the nuget library FbonizziMonoGame to be compatible with UWP or FbonizziMonoGameGallery!

I can do try to di it in my free time for sure!

**Comment by mediaexplorer74** [comment]
> Hi @mediaexplorer74, what a wonderful job, I'm impressed! 😱 Thanks for everything!
> 
> I didn't understand if you want to port the nuget library FbonizziMonoGame to be compatible with UWP or FbonizziMonoGameGallery!
> 
> I can do try to di it in my free time for sure!

Thank you for quick answer. 
FbonizziMonoGame seems to be UWP-compatible (in my fork). But... I can't re-create your FbonizziMonoGameGallery as some UWP demo to understand screen scaling mechanics. I noticed that InFart & Starfall "uwp edition" run fine at different set of windows phones (Lumia 950, Lumia 640) at full-screen mode. However, all another projects at my W10MGameDevQuickie repo fails to do autoscaling :(  I'm trying to solve this mystery via FbonizziMonoGame lib injection :) I can't use your nuget library because of W10M compatibility (W10M  not compatible with netstandard 2.0... only 1.4)

Best,
M.E.

**Comment by FrancescoBonizzi** [comment]
All right, now I understand. 
The porting is all a matter of on which control to render all the "game" of each sample.

In the new year in the free tine I'll try to make a port.

Have a nice new year! 🤣
